import type { INodeProperties } from 'n8n-workflow';

const resource = 'transaction';

export const transactionDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: [resource] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a transaction',
				description: 'Create a new transaction',
				routing: {
					request: { method: 'POST', url: '/transactions' },
				},
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a transaction',
				description: 'Get a transaction by ID',
				routing: {
					request: { method: 'GET', url: '=/transactions/{{$parameter.transactionId}}' },
				},
			},
			{
				name: 'Get Many',
				value: 'getMany',
				action: 'Get many transactions',
				description: 'List transactions with optional filters',
				routing: {
					request: { method: 'GET', url: '/transactions' },
				},
			},
			{
				name: 'Refund',
				value: 'refund',
				action: 'Refund a transaction',
				description: 'Refund a transaction fully or partially',
				routing: {
					request: {
						method: 'POST',
						url: '=/transactions/{{$parameter.transactionId}}/refund',
					},
				},
			},
			{
				name: 'Update Delivery Status',
				value: 'updateDelivery',
				action: 'Update delivery status',
				description: 'Update the delivery status of a transaction',
				routing: {
					request: {
						method: 'PUT',
						url: '=/transactions/{{$parameter.transactionId}}/delivery',
					},
				},
			},
			],
		default: 'create',
	},

	{
		displayName: 'Transaction ID',
		name: 'transactionId',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: {
			show: {
				resource: [resource],
				operation: ['get', 'refund', 'updateDelivery'],
			},
		},

	},

	{
		displayName: 'Amount (Cents)',
		name: 'amount',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: [resource], operation: ['create'] } },
		description: 'Amount in cents (500 = $5.00)',
		routing: { send: { type: 'body', property: 'amount' } },
	},
	{
		displayName: 'Payment Method',
		name: 'paymentMethod',
		type: 'options',
		required: true,
		default: 'pix',
		displayOptions: { show: { resource: [resource], operation: ['create'] } },
		options: [
			{ name: 'Boleto', value: 'boleto' },
			{ name: 'Credit Card', value: 'credit_card' },
			{ name: 'PIX', value: 'pix' },
		],

		routing: { send: { type: 'body', property: 'paymentMethod' } },
	},

	{
		displayName: 'Customer Name',
		name: 'customerName',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: [resource], operation: ['create'] } },

		routing: { send: { type: 'body', property: 'customer.name' } },
	},
	{
		displayName: 'Customer Email',
		name: 'customerEmail',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'email@example.com',
		displayOptions: { show: { resource: [resource], operation: ['create'] } },

		routing: { send: { type: 'body', property: 'customer.email' } },
	},
	{
		displayName: 'Customer',
		name: 'customerFields',
		type: 'collection',
		placeholder: 'Add Customer Field',
		default: {document: {documentValues: { number: '', type: 'cpf' }}},
		displayOptions: { show: { resource: [resource], operation: ['create'] } },
		description: 'Additional customer data',
		options: [
			{
				displayName: 'Document',
				name: 'document',
				type: 'fixedCollection',
				default: { documentValues: { number: '', type: 'cpf' } },
				options: [
					{
						displayName: 'Document',
						name: 'documentValues',
						values: [
							{
								displayName: 'Document Number',
								name: 'number',
								type: 'string',
								default: '',
								description: 'CPF or CNPJ document number',
								routing: { send: { type: 'body', property: 'customer.document.number' } },
							},
							{
								displayName: 'Document Type',
								name: 'type',
								type: 'options',
								default: 'cpf',
								options: [
									{ name: 'CPF', value: 'cpf' },
									{ name: 'CNPJ', value: 'cnpj' },
								],

								routing: { send: { type: 'body', property: 'customer.document.type' } },
							},
						],
					},
				],
			},
			{
				displayName: 'Customer ID',
				name: 'id',
				type: 'string',
				default: '',
				description: 'ID of an existing customer (optional if other fields are filled)',
				routing: { send: { type: 'body', property: 'customer.id' } },
			},
			{
				displayName: 'Phone',
				name: 'phone',
				type: 'string',
				default: '',
				placeholder: '11999999999',
				description: 'Customer phone number',
				routing: { send: { type: 'body', property: 'customer.phone' } },
			},
			{
				displayName: 'External Reference',
				name: 'externalRef',
				type: 'string',
				default: '',
				description: 'External reference for the customer',
				routing: { send: { type: 'body', property: 'customer.externalRef' } },
			},
		],
	},

	{
		displayName: 'Card',
		name: 'cardFields',
		type: 'collection',
		placeholder: 'Add Card Field',
		default: {},
		displayOptions: {
			show: { resource: [resource], operation: ['create'], paymentMethod: ['credit_card'] },
		},
		description: 'Credit card data',
		options: [
			{
				displayName: 'Card Hash',
				name: 'hash',
				type: 'string',
				default: '',
				description: 'Card hash (valid for 5 minutes)',
				routing: { send: { type: 'body', property: 'card.hash' } },
			},
			{
				displayName: 'Card ID',
				name: 'id',
				type: 'number',
				default: 0,
				description: 'ID of a saved card',
				routing: { send: { type: 'body', property: 'card.id' } },
			},
			{
				displayName: 'Card Number',
				name: 'number',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'card.number' } },
			},
			{
				displayName: 'CVV',
				name: 'cvv',
				type: 'string',
				default: '',
				description: 'Security code (CVV)',
				routing: { send: { type: 'body', property: 'card.cvv' } },
			},
			{
				displayName: 'Expiration Month',
				name: 'expirationMonth',
				type: 'number',
				default: 1,
				typeOptions: { minValue: 1, maxValue: 12 },
				routing: { send: { type: 'body', property: 'card.expirationMonth' } },
			},
			{
				displayName: 'Expiration Year',
				name: 'expirationYear',
				type: 'number',
				default: 2025,
				routing: { send: { type: 'body', property: 'card.expirationYear' } },
			},
			{
				displayName: 'Holder Name',
				name: 'holderName',
				type: 'string',
				default: '',
				description: 'Card holder name',
				routing: { send: { type: 'body', property: 'card.holderName' } },
			},
		],
	},
	{
		displayName: 'Installments',
		name: 'installments',
		type: 'number',
		default: 1,
		typeOptions: { minValue: 1, maxValue: 12 },
		displayOptions: {
			show: { resource: [resource], operation: ['create'], paymentMethod: ['credit_card'] },
		},
		description: 'Number of installments (1 to 12)',
		routing: { send: { type: 'body', property: 'installments' } },
	},

	{
		displayName: 'Items',
		name: 'items',
		type: 'fixedCollection',
		typeOptions: { multipleValues: true, multipleValueButtonText: 'Add another item' },
		default: { item: [{ title: '', unitPrice: 0, quantity: 1, tangible: true, additionalFields: {} }] },
		displayOptions: { show: { resource: [resource], operation: ['create'] } },
		description: 'Transaction items',
		options: [
			{
				displayName: 'Item',
				name: 'item',
				values: [
					{
						displayName: 'Additional Fields',
						name: 'additionalFields',
						type: 'collection',
						default: {},
						placeholder: 'Add Field',
						options: [
							{
								displayName: 'External Reference',
								name: 'externalRef',
								type: 'string',
								default: '',
								description: 'External reference for the item',
							},
						]
					},
					{
						displayName: 'Quantity',
						name: 'quantity',
						type: 'number',
						default: 1,
						description: 'Item quantity',
					},
					{
						displayName: 'Tangible',
						name: 'tangible',
						type: 'boolean',
						default: true,
						description: 'Whether the item is a physical product',
					},
					{
						displayName: 'Title',
						name: 'title',
						type: 'string',
						default: '',
						description: 'Item name',
					},
					{
						displayName: 'Unit Price (Cents)',
						name: 'unitPrice',
						type: 'number',
						default: 0,
						description: 'Unit price in cents',
					},
			],
			},
		],
		routing: {
			send: {
				type: 'body',
				property: 'items',
				value: '={{$value.item}}',
			},
		},
	},

	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: [resource], operation: ['create'] } },
		options: [
			{
				displayName: 'Boleto Expires In Days',
				name: 'boletoExpiresInDays',
				type: 'number',
				default: 3,
				description: 'Number of days until boleto expiration',
				routing: { send: { type: 'body', property: 'boleto.expiresInDays' } },
			},
			{
				displayName: 'Customer IP',
				name: 'ip',
				type: 'string',
				default: '',
				description: 'Customer IP address',
				routing: { send: { type: 'body', property: 'ip' } },
			},
			{
				displayName: 'Metadata',
				name: 'metadata',
				type: 'string',
				default: '',
				description: 'Custom metadata for the transaction',
				routing: { send: { type: 'body', property: 'metadata' } },
			},
			{
				displayName: 'PIX Expires In Minutes',
				name: 'pixExpiresInMinutes',
				type: 'number',
				default: 60,
				description: 'Number of minutes until PIX expiration',
				routing: { send: { type: 'body', property: 'pix.expiresInMinutes' } },
			},
			{
				displayName: 'Postback URL',
				name: 'postbackUrl',
				type: 'string',
				default: '',
				description: 'URL to receive transaction updates via webhook',
				routing: { send: { type: 'body', property: 'postbackUrl' } },
			},
			{
				displayName: 'Traceable',
				name: 'traceable',
				type: 'boolean',
				default: false,
				description: 'Whether to enable delivery status management via dashboard',
				routing: { send: { type: 'body', property: 'traceable' } },
			},
		],
	},

	{
		displayName: 'Shipping',
		name: 'shippingFields',
		type: 'collection',
		placeholder: 'Add Shipping Field',
		default: {},
		displayOptions: { show: { resource: [resource], operation: ['create'] } },
		description: 'Shipping information (optional)',
		options: [
			{
				displayName: 'City',
				name: 'city',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'shipping.address.city' } },
			},
			{
				displayName: 'Complement',
				name: 'complement',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'shipping.address.complement' } },
			},
			{
				displayName: 'Country',
				name: 'country',
				type: 'string',
				default: 'br',
				description: 'Country code (e.g. br)',
				routing: { send: { type: 'body', property: 'shipping.address.country' } },
			},
			{
				displayName: 'Fee (Cents)',
				name: 'fee',
				type: 'number',
				default: 0,
				description: 'Shipping fee in cents',
				routing: { send: { type: 'body', property: 'shipping.fee' } },
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				description: 'Recipient name',
				routing: { send: { type: 'body', property: 'shipping.name' } },
			},
			{
				displayName: 'Neighborhood',
				name: 'neighborhood',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'shipping.address.neighborhood' } },
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'string',
				default: '',
				description: 'State code (e.g. SP)',
				routing: { send: { type: 'body', property: 'shipping.address.state' } },
			},
			{
				displayName: 'Street',
				name: 'street',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'shipping.address.street' } },
			},
			{
				displayName: 'Street Number',
				name: 'streetNumber',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'shipping.address.streetNumber' } },
			},
			{
				displayName: 'Zip Code',
				name: 'zipCode',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'shipping.address.zipCode' } },
			},
		],
	},

	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { resource: [resource], operation: ['getMany'] } },
		options: [
			{
				displayName: 'Customer Email',
				name: 'email',
				type: 'string',
				placeholder: 'name@email.com',
				default: '',
				description: 'Customer email to filter by',
				routing: { send: { type: 'query', property: 'email' } },
			},
			{
				displayName: 'Customer Name',
				name: 'name',
				type: 'string',
				default: '',
				description: 'Customer name to filter by',
				routing: { send: { type: 'query', property: 'name' } },
			},
			{
				displayName: 'Delivery Status',
				name: 'deliveryStatus',
				type: 'string',
				default: '',
				description: 'Delivery status: waiting, in_transit, delivered. Separate with commas.',
				routing: { send: { type: 'query', property: 'deliveryStatus' } },
			},
			{
				displayName: 'Document Number',
				name: 'documentNumber',
				type: 'string',
				default: '',
				description: 'Customer CPF/CNPJ document number',
				routing: { send: { type: 'query', property: 'documentNumber' } },
			},
			{
				displayName: 'Installments',
				name: 'installments',
				type: 'string',
				default: '',
				description: 'Number of installments (1 to 12). Separate with commas.',
				routing: { send: { type: 'query', property: 'installments' } },
			},
			{
				displayName: 'Payment Methods',
				name: 'paymentMethods',
				type: 'string',
				default: '',
				description: 'Filter by payment method (credit_card, boleto, pix). Separate with commas.',
				routing: { send: { type: 'query', property: 'paymentMethods' } },
			},
			{
				displayName: 'Phone',
				name: 'phone',
				type: 'string',
				default: '',
				description: 'Customer phone number to filter by',
				routing: { send: { type: 'query', property: 'phone' } },
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'string',
				default: '',
				description:
					'Transaction status. Values: processing, authorized, paid, refunded, waiting_payment, refused, chargedback, canceled, in_protest, partially_paid. Separate with commas',
				routing: { send: { type: 'query', property: 'status' } },
			},
			{
				displayName: 'Traceable',
				name: 'traceable',
				type: 'boolean',
				default: false,
				description: 'Whether to filter by trackable delivery status',
				routing: { send: { type: 'query', property: 'traceable' } },
			},
			{
				displayName: 'Transaction ID',
				name: 'id',
				type: 'number',
				default: 0,
				description: 'Filter by transaction ID',
				routing: { send: { type: 'query', property: 'id' } },
			},
		],
	},

	{
		displayName: 'Refund Amount (Cents)',
		name: 'refundAmount',
		type: 'number',
		default: 0,
		displayOptions: { show: { resource: [resource], operation: ['refund'] } },
		description: 'Refund amount in cents. If not provided, the full amount or remaining balance will be refunded.',
		routing: {
			send: {
				type: 'body',
				property: 'amount',
				value: '={{ $value || undefined }}',
			},
		},
	},

	{
		displayName: 'Delivery Status',
		name: 'deliveryStatusValue',
		type: 'options',
		required: true,
		default: 'waiting',
		displayOptions: { show: { resource: [resource], operation: ['updateDelivery'] } },
		options: [
			{ name: 'Waiting', value: 'waiting' },
			{ name: 'In Transit', value: 'in_transit' },
			{ name: 'Delivered', value: 'delivered' },
		],
		description: 'New delivery status',
		routing: { send: { type: 'body', property: 'status' } },
	},
	{
		displayName: 'Tracking Code',
		name: 'trackingCode',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: [resource], operation: ['updateDelivery'] } },
		description: 'Tracking code (optional)',
		routing: {
			send: {
				type: 'body',
				property: 'trackingCode',
				value: '={{ $value || undefined }}',
			},
		},
	},

];
